/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TodoList {
    'arraytodo': any[];
    'btncolor': string;
    'fontcolorbtn': string;
    'getTodoList': () => Promise<any[]>;
    'pushTodoList': (task: any, did?: boolean) => Promise<void>;
    'setTodoList': (list: any) => Promise<void>;
    'shadow_color': string;
    'textadd': string;
    'textremove': string;
    'titlebox': string;
  }
}

declare global {


  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    'todo-list': HTMLTodoListElement;
  }
}

declare namespace LocalJSX {
  interface TodoList {
    'arraytodo'?: any[];
    'btncolor'?: string;
    'fontcolorbtn'?: string;
    'shadow_color'?: string;
    'textadd'?: string;
    'textremove'?: string;
    'titlebox'?: string;
  }

  interface IntrinsicElements {
    'todo-list': TodoList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'todo-list': LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
    }
  }
}


